package htmlparser

func initElements() {
	allElements = []HtmlElementInfo{
		HtmlElementInfo{
			TagName:                "a",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"href", "target", "rel", "hreflang", "media", "type"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{"coords", "shape", "urn", "charset", "methods", "rev", "name"},
		},
		HtmlElementInfo{
			TagName:                "abbr",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "acronym",
			HtmlVersion:            4,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "address",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "applet",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "area",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"alt", "href", "target", "rel", "media", "hreflang", "type", "shape", "coords"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{"map"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"nohref"},
		},
		HtmlElementInfo{

			TagName:                "article",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "aside",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "audio",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETFlow | HETPhrasing,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"autoplay", "preload", "controls", "loop", "mediagroup", "muted", "src"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "b",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "base",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"href", "target"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{"head"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "basefont",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "bdi",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "bdo",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "big",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "blockquote",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"cite"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "body",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{"script", "style"},
			attributesString:       []string{"onafterprint", "onbeforeprint", "onbeforeunload", "onblur", "onerror", "onfocus", "onhaschange", "onload", "onmessage", "onoffline", "ononline", "onpagehide", "onpageshow", "onpopstate", "onresize", "onstoragte", "onunload"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"html"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"alink", "background", "bgcolor", "link", "marginbottom", "marginheight", "marginleft", "marginright", "margintop", "marginwidth", "text", "vlink"},
		},
		HtmlElementInfo{

			TagName:                "br",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{"clear"},
		},
		HtmlElementInfo{

			TagName:                "button",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "disabled", "form", "type", "value", "formaction", "autofocus", "formenctype", "formmethod", "formtarget", "formnovalidate"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "canvas",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"height", "width"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "caption",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"table"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "center",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "cite",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "code",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "col",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"span"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{"colgroup"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"align", "width", "char", "charoff", "valign"},
		},
		HtmlElementInfo{

			TagName:                "colgroup",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"span"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"table"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"width", "char", "charoff", "valign"},
		},
		HtmlElementInfo{

			TagName:                "command",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"type", "label", "icon", "disabled", "radiogroup", "checked"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing | HETMeta,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "datalist",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "dd",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"dl"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "del",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"cite", "datetime"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "details",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"open"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "dfn",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "dir",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "div",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "dl",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"compact"},
		},
		HtmlElementInfo{

			TagName:                "dt",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"dl"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "em",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "embed",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "fieldset",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "disabled", "form"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "figcaption",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"figure"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "figure",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "font",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "footer",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"header", "footer", "address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "form",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"action", "method", "enctype", "name", "accept-charset", "novalidate", "target", "autocomplete"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"form"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "frame",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "frameset",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "h1",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"hgroup"},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "h2",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"hgroup"},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "h3",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"hgroup"},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "h4",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"hgroup"},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "h5",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"hgroup"},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "h6",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"hgroup"},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "head",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETMeta,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"html"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"profile"},
		},
		HtmlElementInfo{

			TagName:                "header",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"footer", "address", "header"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "hgroup",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"h1", "h2", "h3", "h4", "h5", "h6"},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "hr",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align", "width", "noshade", "size", "color"},
		},
		HtmlElementInfo{

			TagName:                "html",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"head", "body"},
			attributesString:       []string{"manifest"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"version"},
		},
		HtmlElementInfo{

			TagName:                "i",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "iframe",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"src", "srcdoc", "name", "width", "height", "sandbox", "seamless"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{"longdesc", "align", "allowtransparency", "frameborder", "marginheight", "marginwidth", "scrolling"},
		},
		HtmlElementInfo{

			TagName:                "img",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"src", "alt", "height", "width", "usemap", "ismap", "border"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{"longdesc", "name", "align", "hspace", "vspace", "border"},
		},
		HtmlElementInfo{

			TagName:                "input",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "disabled", "form", "type", "maxlength", "readonly", "size", "value", "autocomplete", "autofocus", "list", "pattern", "required", "placeholder", "dirname", "checked", "formaction", "formenctype", "formmethod", "formtarget", "formnovalidate", "accept", "multiple", "alt", "src", "height", "width", "list", "min", "max", "step"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{"usemap", "align"},
		},
		HtmlElementInfo{

			TagName:                "ins",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"cite", "datetime"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "isindex",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "kbd",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "keygen",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"challenge", "keytype", "autofocus", "name", "disabled", "form"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "label",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"for", "form"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "legend",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"fieldset"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "li",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"value"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"ul", "ol", "menu"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "link",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"href", "rel", "hreflang", "media", "type", "sizes"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{"noscript"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETMeta,
			ObsoleteAttributes:     []string{"target", "urn", "charset", "methods", "rev"},
		},
		HtmlElementInfo{

			TagName:                "map",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "mark",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "menu",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"type", "label"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"compact"},
		},
		HtmlElementInfo{

			TagName:                "meta",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "content", "http-equiv", "charset"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETMeta,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "meter",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"value", "min", "low", "high", "max", "optimum"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "nav",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"address"},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "nobr",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "noframes",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "noscript",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETMeta | HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"noscript"},
			ParentContentTypes:     HETMeta | HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "object",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"data", "type", "height", "width", "usemap", "name", "form"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{"archive", "classid", "code", "codebase", "codetype", "declare", "standby", "align", "hspace", "vspace", "border"},
		},
		HtmlElementInfo{

			TagName:                "ol",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"li"},
			attributesString:       []string{"start", "reversed", "type"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"compact"},
		},
		HtmlElementInfo{

			TagName:                "optgroup",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"option"},
			attributesString:       []string{"label", "disabled"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"select"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "option",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"disabled", "selected", "label", "value"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"optgroup", "select", "datalist"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"name"},
		},
		HtmlElementInfo{

			TagName:                "output",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "form", "for"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "p",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"align"},
		},
		HtmlElementInfo{

			TagName:                "param",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "value"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{"object"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"type", "valuetype"},
		},
		HtmlElementInfo{

			TagName:                "pre",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "progress",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"value", "max"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "q",
			HtmlVersion:            4,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"cite"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "rp",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"ruby"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "rt",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"ruby"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "ruby",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "s",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "samp",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "script",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNRCharData,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"type", "src", "defer", "async", "charset"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETMeta | HETPhrasing | HETFlow,
			ObsoleteAttributes:     []string{"language"},
		},
		HtmlElementInfo{

			TagName:                "section",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{"style"},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "select",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"optgroup", "option"},
			attributesString:       []string{"name", "disabled", "form", "size", "multiple", "autofocus", "required"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "small",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "source",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"src", "type", "media"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"audio", "video"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "span",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "strike",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "strong",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "style",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNRCharData,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"type", "media", "scoped"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"div", "noscript", "section", "article", "aside"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETMeta,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "sub",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "summary",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"details"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "sup",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "table",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"capition", "colgroup", "thead", "tfoot", "tbody", "tr"},
			attributesString:       []string{"border"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"summary", "align", "width", "bgcolor", "cellpadding", "cellspacing", "frame", "rules"},
		},
		HtmlElementInfo{

			TagName:                "tbody",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"tr"},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"table"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"align", "char", "charoff", "valign"},
		},
		HtmlElementInfo{

			TagName:                "td",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"colspan", "rowspan", "headers"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"tr"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"scope", "abbr", "axis", "align", "width", "char", "charoff", "valign", "bgcolor", "height", "nowrap"},
		},
		HtmlElementInfo{

			TagName:                "textarea",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"name", "disabled", "form", "readonly", "maxlength", "autofocus", "required", "placeholder", "dirname", "rows", "wrap", "cols"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "tfoot",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"tr"},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"table"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"align", "char", "charoff", "valign"},
		},
		HtmlElementInfo{

			TagName:                "th",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"scope", "scolspan", "rowspan", "headers"},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"tr"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"scope", "abbr", "axis", "align", "width", "char", "charoff", "valign", "bgcolor", "height", "nowrap"},
		},
		HtmlElementInfo{

			TagName:                "thead",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"tr"},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"table"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"align", "char", "charoff", "valign"},
		},
		HtmlElementInfo{

			TagName:                "time",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"datetime"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"time"},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "title",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{"head"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "tr",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"td", "th"},
			attributesString:       []string{},
			TagFormatting:          HTFOptionalClosing,
			ParentTags:             []string{"table", "thead", "tfoot", "tbody"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{"align", "char", "charoff", "valign", "bgcolor"},
		},
		HtmlElementInfo{

			TagName:                "track",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETMeta,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"kind", "src", "srclang", "label", "default"},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{"audio", "video"},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETNone,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "tt",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "u",
			HtmlVersion:            3,
			Obsolete:               true,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "ul",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{"li"},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETFlow,
			ObsoleteAttributes:     []string{"type", "compact"},
		},
		HtmlElementInfo{

			TagName:                "var",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETPhrasing | HETText,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "video",
			HtmlVersion:            5,
			Obsolete:               false,
			ElementType:            HETFlow,
			PermittedChildrenTypes: HETAnyContent,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{"autoplay", "preload", "controls", "loop", "poster", "height", "width", "mediagroup", "muted", "src"},
			TagFormatting:          HTFComplete,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{"a", "button"},
			ParentContentTypes:     HETFlow | HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
		HtmlElementInfo{

			TagName:                "wbr",
			HtmlVersion:            3,
			Obsolete:               false,
			ElementType:            HETPhrasing,
			PermittedChildrenTypes: HETNone,
			PermittedChildrenTags:  []string{},
			attributesString:       []string{},
			TagFormatting:          HTFSingle,
			ParentTags:             []string{},
			ExcludeParentTags:      []string{},
			ParentContentTypes:     HETPhrasing,
			ObsoleteAttributes:     []string{},
		},
	}

}
