package htmlparser

func initElements() {
	AllElements: []HtmlElementInfo{
				HtmlElementInfo{ 
					TagName: "a",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "href;target;rel;hreflang;media;type",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "coords;shape;urn;charset;methods;rev;name",
				},
				HtmlElementInfo{
					TagName: "abbr",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "acronym",
					HtmlVersion: 4,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "address",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "applet",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "area",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "alt;href;target;rel;media;hreflang;type;shape;coords",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "map",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "nohref",
				},
				HtmlElementInfo{

					TagName: "article",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "aside",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "audio",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					PermittedChildrenTagsString: "",
					AttributesString: "autoplay;preload;controls;loop;mediagroup;muted;src",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "b",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "base",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "href;target",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "head",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "basefont",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "bdi",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "bdo",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "big",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "blockquote",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "cite",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "body",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "script;style",
					AttributesStrin: "onafterprint;onbeforeprint;onbeforeunload;onblur;onerror;onfocus;onhaschange;onload;onmessage;onoffline;ononline;onpagehide;onpageshow;onpopstate;onresize;onstoragte;onunload;",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "html",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "alink;background;bgcolor;link;marginbottom;marginheight;marginleft;marginright;margintop;marginwidth;text;vlink",
				},
				HtmlElementInfo{

					TagName: "br",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "clear",
				},
				HtmlElementInfo{

					TagName: "button",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "name;disabled;form;type;value;formaction;autofocus;formenctype;formmethod;formtarget;formnovalidate",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "canvas",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "height;width",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "caption",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "table",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "center",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "cite",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "code",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "col",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "span",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "colgroup",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "align;width;char;charoff;valign",
				},
				HtmlElementInfo{

					TagName: "colgroup",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "span",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "table",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "width;char;charoff;valign",
				},
				HtmlElementInfo{

					TagName: "command",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "type;label;icon;disabled;radiogroup;checked;",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing | HtmlElementType.Meta,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "datalist",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "dd",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "dl",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "del",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "cite;datetime",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "details",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "open",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "dfn",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "dir",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "div",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "dl",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "compact",
				},
				HtmlElementInfo{

					TagName: "dt",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "dl",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "em",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "embed",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "fieldset",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "name;disabled;form",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "figcaption",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "figure",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "figure",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "font",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "footer",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "header;footer;address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "form",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "action;method;enctype;name;accept-charset;novalidate;target;autocomplete",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "form",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "frame",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "frameset",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "h1",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "hgroup",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "h2",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "hgroup",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "h3",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "hgroup",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "h4",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "hgroup",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "h5",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "hgroup",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "h6",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "hgroup",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "head",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.Meta,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "html",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "profile",
				},
				HtmlElementInfo{

					TagName: "header",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "footer;address;header",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "hgroup",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "h1;h2;h3;h4;h5;h6",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "hr",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align;width;noshade;size;color",
				},
				HtmlElementInfo{

					TagName: "html",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "head;body",
					AttributesString: "manifest",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "version",
				},
				HtmlElementInfo{

					TagName: "i",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "iframe",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "src;srcdoc;name;width;height;sandbox;seamless;",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "longdesc;align;allowtransparency;frameborder;marginheight;marginwidth;scrolling",
				},
				HtmlElementInfo{

					TagName: "img",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "src;alt;height;width;usemap;ismap;border",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "longdesc;name;align;hspace;vspace;border",
				},
				HtmlElementInfo{

					TagName: "input",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "name;disabled;form;type;maxlength;readonly;size;value;autocomplete;autofocus;list;pattern;required;placeholder;dirname;checked;formaction;formenctype;formmethod;formtarget;formnovalidate;accept;multiple;alt;src;height;width;list;min;max;step;",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "usemap;align",
				},
				HtmlElementInfo{

					TagName: "ins",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "cite;datetime",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "isindex",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "kbd",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "keygen",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "challenge;keytype;autofocus;name;disabled;form",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "label",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "for;form",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "legend",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "fieldset",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "li",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "value",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "ul;ol;menu",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "link",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "href;rel;hreflang;media;type;sizes",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "noscript",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Meta,
					ObsoleteAttributesString: "target;urn;charset;methods;rev",
				},
				HtmlElementInfo{

					TagName: "map",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "name",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "mark",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "menu",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "type;label",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "compact",
				},
				HtmlElementInfo{

					TagName: "meta",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "name;content;http-equiv;charset;",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Meta,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "meter",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "value;min;low;high;max;optimum",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "nav",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "address",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "nobr",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "noframes",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "noscript",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.Meta | HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "noscript",
					ParentContentTypes: HtmlElementType.Meta | HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "object",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "data;type;height;width;usemap;name;form",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "archive;classid;code;codebase;codetype;declare;standby;align;hspace;vspace;border",
				},
				HtmlElementInfo{

					TagName: "ol",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "li",
					AttributesString: "start;reversed;type",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "compact",
				},
				HtmlElementInfo{

					TagName: "optgroup",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "option",
					AttributesString: "label;disabled",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "select",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "option",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "disabled;selected;label;value",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "optgroup;select;datalist",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "name",
				},
				HtmlElementInfo{

					TagName: "output",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "name;form;for",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "p",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "align",
				},
				HtmlElementInfo{

					TagName: "param",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "name;value",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "object",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "type;valuetype",
				},
				HtmlElementInfo{

					TagName: "pre",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "progress",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "value;max",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "q",
					HtmlVersion: 4,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "cite",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "rp",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "ruby",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "rt",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "ruby",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "ruby",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "s",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "samp",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "script",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.NRCharData,
					PermittedChildrenTagsString: "",
					AttributesString: "type;src;defer;async;charset",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Meta | HtmlElementType.Phrasing | HtmlElementType.Flow,
					ObsoleteAttributesString: "language",
				},
				HtmlElementInfo{

					TagName: "section",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "style",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "select",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "optgroup;option",
					AttributesString: "name;disabled;form;size;multiple;autofocus;required",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "small",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "source",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "src;type;media",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "audio;video",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "span",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "strike",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "strong",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "style",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.NRCharData,
					PermittedChildrenTagsString: "",
					AttributesString: "type;media;scoped",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "div;noscript;section;article;aside",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Meta,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "sub",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "summary",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "details",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "sup",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "table",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "capition;colgroup;thead;tfoot;tbody;tr",
					AttributesString: "border",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "summary;align;width;bgcolor;cellpadding;cellspacing;frame;rules",
				},
				HtmlElementInfo{

					TagName: "tbody",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "tr",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "table",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "align;char;charoff;valign",
				},
				HtmlElementInfo{

					TagName: "td",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "colspan;rowspan;headers",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "tr",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "scope;abbr;axis;align;width;char;charoff;valign;bgcolor;height;nowrap",
				},
				HtmlElementInfo{

					TagName: "textarea",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "name;disabled;form;readonly;maxlength;autofocus;required;placeholder;dirname;rows;wrap;cols",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "tfoot",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "tr",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "table",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "align;char;charoff;valign",
				},
				HtmlElementInfo{

					TagName: "th",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "scope;scolspan;rowspan;headers",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "tr",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "scope;abbr;axis;align;width;char;charoff;valign;bgcolor;height;nowrap",
				},
				HtmlElementInfo{

					TagName: "thead",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "tr",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "table",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "align;char;charoff;valign",
				},
				HtmlElementInfo{

					TagName: "time",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "datetime",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "time",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "title",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "head",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "tr",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "td;th",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.OptionalClosing,
					ParentTagsString: "table;thead;tfoot;tbody",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "align;char;charoff;valign;bgcolor",
				},
				HtmlElementInfo{

					TagName: "track",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Meta,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "kind;src;srclang;label;default",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "audio;video",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.None,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "tt",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "u",
					HtmlVersion: 3,
					Obsolete: true,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "ul",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "li",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Flow,
					ObsoleteAttributesString: "type;compact",
				},
				HtmlElementInfo{

					TagName: "var",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.Phrasing | HtmlElementType.Text,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "video",
					HtmlVersion: 5,
					Obsolete: false,
					ElementType: HtmlElementType.Flow,
					PermittedChildrenTypes: HtmlElementType.AnyContent,
					PermittedChildrenTagsString: "",
					AttributesString: "autoplay;preload;controls;loop;poster;height;width;mediagroup;muted;src",
					TagFormatting: HtmlTagFormatting.Complete,
					ParentTagsString: "",
					ExcludeParentTagsString: "a;button",
					ParentContentTypes: HtmlElementType.Flow | HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
				HtmlElementInfo{

					TagName: "wbr",
					HtmlVersion: 3,
					Obsolete: false,
					ElementType: HtmlElementType.Phrasing,
					PermittedChildrenTypes: HtmlElementType.None,
					PermittedChildrenTagsString: "",
					AttributesString: "",
					TagFormatting: HtmlTagFormatting.Single,
					ParentTagsString: "",
					ExcludeParentTagsString: "",
					ParentContentTypes: HtmlElementType.Phrasing,
					ObsoleteAttributesString: "",
				},
			}
	
	
}
